import type { Project, WorkspaceState } from './types';

const baseProject = (id:string,name:string,domain:string,color:string,gateIndex:number): Project => ({
  id,name,domain,color,gateIndex,gate:['Setup','Discover','Clarify','Define','Validate','Approve'][gateIndex] as Project['gate'],health:id==='leave'?91:id==='returns'?76:82,documentSyncProposals:[],
  description:id==='loan'?'Create an inclusive, traceable mobile lending journey with controlled automated decisions.':id==='leave'?'Improve employee leave requests while protecting sensitive workforce information.':'Design a fair, evidence-led returns process with a human appeal path.',
  folderName:`BA-Mate/${id}-workspace`,template:id==='loan'?'Retail banking':id==='leave'?'People operations':'Retail and e-commerce',
  governancePacks:['Core responsible BA',id==='loan'?'Financial services fairness':id==='leave'?'Workforce privacy':'Consumer fairness'],
  sources:[
    {id:'SRC-01',name:id==='loan'?'Stakeholder_interview_notes.pdf':id==='leave'?'HR_leave_policy.docx':'Returns_policy_2026.pdf',type:id==='leave'?'DOCX':'PDF',status:'Analyzed',classification:'Project only',provenance:'Uploaded by Nimnada K.',concepts:id==='loan'?['decision time','manual review','identity','appeal']:id==='leave'?['leave balance','delegation','team coverage']:['return window','image evidence','human review'],approved:true,immutable:true},
    {id:'SRC-02',name:id==='loan'?'Retail_lending_policy_2026.pdf':id==='leave'?'Accessibility_standard.pdf':'Customer_service_notes.txt',type:id==='returns'?'TXT':'Policy',status:'Analyzed',classification:id==='loan'?'Confidential':'Project only',provenance:'Organization policy pack',concepts:['retention','accessibility','authorization'],approved:true,immutable:true},
    {id:'SRC-03',name:'Legacy_process_notes.txt',type:'TXT',status:'Needs review',classification:'Project only',provenance:'Project folder',concepts:['legacy exception','unverified SLA'],approved:false,immutable:true}
  ],
  clarifications:[
    {id:'CQ-01',priority:'Blocking',question:id==='loan'?'Which applicant types must always enter manual review?':id==='leave'?'Who may approve leave when the line manager is unavailable?':'Which product categories support photo-based assessment?',rationale:'The decision boundary changes the workflow and human accountability.',sourceId:'SRC-01',owner:'Product owner',status:'Unanswered',suggestions:['All high-risk cases','Only policy-defined exceptions','Use a custom answer'],affects:['FR-01','US-01','DGM-01']},
    {id:'CQ-02',priority:'Important',question:id==='loan'?'What measurable target defines a fast standard decision?':id==='leave'?'What team coverage threshold triggers a warning?':'How long should uploaded evidence be retained?',rationale:'A measurable constraint is required for testable acceptance criteria.',sourceId:'SRC-01',owner:'Business analyst',status:'Answered',answer:id==='loan'?'95% within 60 seconds':'Confirm against organization policy',suggestions:['Within 30 seconds','Within 60 seconds','Use a custom answer'],affects:['NFR-01','AC-02']},
    {id:'CQ-03',priority:'Optional',question:'Should the user receive an accessible explanation when a request needs review?',rationale:'Improves transparency and inclusion without changing the core outcome.',sourceId:'SRC-02',owner:'Accessibility lead',status:'Deferred',suggestions:['Yes, plain-language status','Yes, with support contact','Keep open'],affects:['NFR-03']}
  ],
  requirements:[
    {id:'FR-01',kind:'Functional',title:id==='loan'?'Submit a mobile loan application':id==='leave'?'Submit and route a leave request':'Start an eligible return',statement:id==='loan'?'The system shall allow an authenticated eligible customer to submit a personal-loan application and receive either a decision or manual-review status.':id==='leave'?'The system shall allow an employee to submit a leave request and route it to an authorized approver.':'The system shall show eligibility and evidence requirements before a customer submits a return.',priority:'Must',status:'approved',owner:'Nimnada K.',sourceIds:['SRC-01'],storyIds:['US-01'],checkIds:['CHK-01','CHK-02'],version:4,rationale:'Users need a controlled digital entry point with a visible outcome.',businessValue:'Reduce handling time while retaining accountable human escalation.',businessRules:['Only authenticated eligible users may submit','Policy exceptions route to an authorized reviewer'],fitCriteria:['A valid request is recorded with a unique identifier','Every exception exposes its review status'],dependencies:['Identity service','Policy decision service'],stakeholders:['Product owner','Compliance lead'],openQuestions:[],comments:[],syncStatus:'Synced'},
    {id:'NFR-01',kind:'Non-functional',title:'Performance and inclusive status',statement:id==='loan'?'95% of standard automated decisions shall return a decision or review status within 60 seconds, with accessible status updates.':'Primary task views shall load within two seconds and expose status to assistive technology.',priority:'Should',status:'in-review',owner:'Nimnada K.',sourceIds:['SRC-02'],storyIds:['US-01'],checkIds:['CHK-03'],version:2,rationale:'Users require a predictable and accessible service experience.',businessValue:'Reduce abandonment and support demand.',businessRules:['Performance excludes scheduled maintenance'],fitCriteria:['95th percentile measured over an agreed production window'],dependencies:['Monitoring service'],stakeholders:['Accessibility lead','Service owner'],openQuestions:['Confirm the production measurement window'],comments:[],syncStatus:'Not included'}
  ],
  stories:[{id:'US-01',role:id==='leave'?'employee':id==='returns'?'online customer':'eligible retail banking customer',goal:id==='leave'?'submit and track a leave request':id==='returns'?'submit an eligible return with evidence':'apply for a personal loan in the mobile app',value:id==='leave'?'I can plan time away with confidence':id==='returns'?'I can resolve a return without unnecessary support calls':'I can request credit without visiting a branch',priority:'Must',status:'approved',requirementIds:['FR-01'],criteria:['Given an authenticated eligible user, when the request is submitted, then the system records it and displays its status.','Given a policy exception, when automated checks complete, then the request is routed to an authorized human reviewer.'],version:3,epic:'Digital request journey',feature:'Request submission and status',owner:'Nimnada K.',dependencies:['FR-01'],sourceIds:['SRC-01'],comments:[],syncStatus:'Synced'}],
  registers:[
    {id:'STK-01',type:'Stakeholder',title:'Product owner',owner:'Product team',status:'approved'},
    {id:'ASM-01',type:'Assumption',title:id==='loan'?'Draft applications are retained for 30 days':'Existing identity and authorization services can be reused',owner:'Data protection officer',severity:'High',status:'open',due:'Aug 18'},
    {id:'RSK-01',type:'Risk',title:'Policy conflict may create inconsistent review outcomes',owner:'Compliance lead',severity:'Medium',status:'open'}
  ],
  traceLinks:[
    {id:'TL-01',from:'SRC-01',to:'FR-01',relation:'supports',status:'Verified'},
    {id:'TL-02',from:'CQ-02',to:'NFR-01',relation:'clarifies',status:'Verified'},
    {id:'TL-03',from:'FR-01',to:'US-01',relation:'realized by',status:'Verified'},
    {id:'TL-04',from:'US-01',to:'DGM-01',relation:'visualized by',status:'Pending'}
  ],
  checks:[
    {id:'CHK-01',category:'Human governance',title:'Explicit BA approval is required',status:'Passed',source:'Core responsible BA',rationale:'AI suggestions cannot become final automatically.',owner:'Lead BA',immutable:true},
    {id:'CHK-02',category:'Privacy',title:id==='loan'?'Retention period is unsupported':'Sensitive data visibility is restricted',status:id==='loan'?'Blocking':'Passed',source:id==='loan'?'Financial services fairness':'Workforce privacy',rationale:id==='loan'?'The proposed 30-day value is not linked to an approved policy.':'Only authorized roles can view sensitive details.',owner:'Data protection officer'},
    {id:'CHK-03',category:'Accessibility',title:'Accessible status and explanation',status:'Warning',source:'Core responsible BA',rationale:'The main success path is covered; the exception explanation still needs confirmation.',owner:'Accessibility lead'},
    {id:'CHK-04',category:'Traceability',title:'Source-to-artifact coverage',status:'Passed',source:'Project rules',rationale:'Primary requirements retain source and clarification links.',owner:'Business analyst'}
  ],
  diagrams:[{id:'DGM-01',name:id==='loan'?'Loan application decision flow':'Primary request workflow',type:'Flowchart',source:'flowchart TD\n  A[Request started] --> B[Validate input]\n  B --> C{Policy checks}\n  C -->|Pass| D[Show outcome]\n  C -->|Exception| E[Human review]',linkedIds:['FR-01','US-01'],version:3,status:'Approved',approvalStatus:'Approved',comments:[],versions:[{version:3,source:'flowchart TD\n  A[Request started] --> B[Validate input]\n  B --> C{Policy checks}\n  C -->|Pass| D[Show outcome]\n  C -->|Exception| E[Human review]',at:'Today, 09:10',actor:'Nimnada K.',note:'Approved workflow'}]}],
  documents:[{id:'DOC-01',name:id==='loan'?'Mobile lending SRS':'Project requirements specification',template:'Software Requirements Specification',status:'draft',version:4,receipts:[{id:'SYNC-01',at:'Today, 09:25',documentVersion:4,artifactVersions:[{id:'FR-01',version:4},{id:'US-01',version:3}],acceptedBlockIds:['BLK-02']}],comments:[],sections:[{id:'SEC-01',title:'1. Purpose and scope',content:'This specification describes the approved scope, actors, constraints and safeguards for the project.',linkedIds:['FR-01'],comments:[],blocks:[{id:'BLK-01',type:'paragraph',content:'This specification describes the approved scope, actors, constraints and safeguards for the project.',linkedIds:['FR-01']}]},{id:'SEC-02',title:'2. Functional requirements',content:'FR-01 defines the primary request workflow and controlled exception handling.',linkedIds:['FR-01','US-01'],comments:[],blocks:[{id:'BLK-02',type:'requirements-table',content:'FR-01 — Primary request workflow and controlled exception handling.',linkedIds:['FR-01','US-01']}]},{id:'SEC-03',title:'3. Quality and safeguards',content:'Human approval, traceability, privacy and accessibility remain mandatory quality gates.',linkedIds:['NFR-01','CHK-01','CHK-02'],comments:[],blocks:[{id:'BLK-03',type:'callout',content:'Human approval, traceability, privacy and accessibility remain mandatory quality gates.',linkedIds:['NFR-01','CHK-01','CHK-02']}]}]}],
  changes:[{id:'CR-01',title:'Reduce the standard decision target to 45 seconds',rationale:'New service benchmark requested by the product owner.',source:'Planning workshop · Aug 9',status:'Impact review',impacts:[{id:'NFR-01',type:'Requirement',reason:'Performance threshold changes',selected:true},{id:'US-01',type:'User story',reason:'Acceptance criterion contains 60-second target',selected:true},{id:'DGM-01',type:'Diagram',reason:'Decision-service annotation may be stale',selected:false},{id:'DOC-01',type:'Document',reason:'SRS quality section references the target',selected:true}]}],
  versions:[{id:'VER-04',label:'Current working draft',version:'v0.4',at:'Today, 10:32',actor:'Nimnada K.',type:'Autosave',locked:false,changes:'Clarification response and NFR updated'},{id:'VER-03',label:'Discovery milestone',version:'v0.3',at:'Aug 9, 16:20',actor:'Nimnada K.',type:'Snapshot',locked:false,changes:'First structured artifact set'},{id:'VER-02',label:'Initial approved baseline',version:'B1',at:'Aug 7, 11:10',actor:'Lead BA',type:'Baseline',locked:true,changes:'Approved intake and scope'}],
  audit:[{id:'EV-01',at:'10:32',actor:'Nimnada K.',action:'Answered clarification',object:'CQ-02',detail:'Added measurable target and regenerated linked checks.'},{id:'EV-02',at:'10:29',actor:'BA Mate',action:'Proposed revision',object:'NFR-01',detail:'Suggestion retained as draft pending BA review.'},{id:'EV-03',at:'Yesterday',actor:'Lead BA',action:'Created snapshot',object:'v0.3',detail:'Discovery milestone recorded.'}],
  conversations:[{id:'CONV-01',title:'Clarify decision rules',context:[{id:'SRC-01',type:'Source',label:'Stakeholder interview notes',origin:'attached',removable:true,route:'sources'},{id:'FR-01',type:'Requirement',label:'Submit a request',version:4,origin:'mentioned',removable:true,route:'artifacts'}],updated:'2 min ago',messages:[{id:'M-01',role:'user',text:'Review @FR-01 and identify anything that prevents testable acceptance criteria.',references:[{id:'FR-01',type:'Requirement',label:'Submit a request',version:4}]},{id:'M-02',role:'assistant',text:'I found one blocking question and a measurable-quality gap. I used SRC-01 and FR-01 v4. I can propose an update, but it will not change the artifact until you accept the diff.',references:[{id:'SRC-01',type:'Source',label:'Stakeholder interview notes'},{id:'FR-01',type:'Requirement',label:'Submit a request',version:4}],proposal:{id:'PROP-01',kind:'requirement-revision',target:'NFR-01',before:'Decisions should be returned quickly.',after:'95% of standard decisions return a decision or manual-review status within 60 seconds.',status:'pending',references:[{id:'SRC-01',type:'Source',label:'Stakeholder interview notes'}],impact:['US-01','DGM-01','DOC-01']}}]}],
  goals:[{id:'GOAL-01',title:'Primary project delivery',kind:'New discovery',status:'Active',description:'Establish and deliver the initial governed business-analysis scope.',createdAt:'Demonstration workspace',gate:['Setup','Discover','Clarify','Define','Validate','Approve'][gateIndex] as Project['gate'],gateIndex,conversationId:'CONV-01',sourceIds:['SRC-01','SRC-02'],deliverables:['FR-01','NFR-01','US-01','DGM-01','DOC-01','CR-01']}],
  activeGoalId:'GOAL-01',
  members:[{id:'MEM-01',name:'Nimnada K.',initials:'NK',role:'Owner / Lead BA',approval:true,status:'Active'},{id:'MEM-02',name:'Amara P.',initials:'AP',role:'BA Editor',approval:false,status:'Active'},{id:'MEM-03',name:'Compliance reviewer',initials:'CR',role:'Reviewer',approval:false,status:'Invited'}]
});

export const seedState: WorkspaceState = {schemaVersion:5,
  projects:[baseProject('loan','Mobile loan onboarding','Retail banking','#7158d9',4),baseProject('leave','Employee leave portal','People operations','#2f8f79',5),baseProject('returns','Smart returns workflow','E-commerce','#d27a38',3)],
  evaluationRuns:[{id:'EVAL-014',caseId:'CASE-03',condition:'Proposed workflow',evaluatorCode:'BA-014',datasetVersion:'2026.07',prototypeVersion:'BA Mate 0.2.0',model:'synthetic/demo-model',promptVersion:'adaptive-ba-v3',duration:'12:48',status:'Complete'},{id:'EVAL-015',caseId:'CASE-04',condition:'Generic AI',evaluatorCode:'BA-015',datasetVersion:'2026.07',prototypeVersion:'BA Mate 0.2.0',model:'synthetic/demo-model',promptVersion:'generic-v1',duration:'00:00',status:'Ready'}],
  telemetryEvents:[],
  stageFeedback:[]
};
